# Generated by Django 4.2.4 on 2023-08-20 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="like",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="article",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="article",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="created_at",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
